service: bigdateros-bot

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: False

functions:
 app:
   handler: wsgi.handler
   events:
     - http: ANY /
     - http: 'ANY /{proxy+}'